/*
 * This file is generated by jOOQ.
 */
package com.back.jooq;


import com.back.jooq.tables.Category;
import com.back.jooq.tables.ChatMember;
import com.back.jooq.tables.ChatMessage;
import com.back.jooq.tables.ChatRoom;
import com.back.jooq.tables.Member;
import com.back.jooq.tables.Notification;
import com.back.jooq.tables.Post;
import com.back.jooq.tables.PostFavorite;
import com.back.jooq.tables.PostImage;
import com.back.jooq.tables.PostOption;
import com.back.jooq.tables.PostRegion;
import com.back.jooq.tables.Region;
import com.back.jooq.tables.Report;
import com.back.jooq.tables.Reservation;
import com.back.jooq.tables.ReservationLog;
import com.back.jooq.tables.ReservationOption;
import com.back.jooq.tables.Review;
import com.back.jooq.tables.VectorStore;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Chwimeet extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>chwimeet</code>
     */
    public static final Chwimeet CHWIMEET = new Chwimeet();

    /**
     * The table <code>chwimeet.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>chwimeet.chat_member</code>.
     */
    public final ChatMember CHAT_MEMBER = ChatMember.CHAT_MEMBER;

    /**
     * The table <code>chwimeet.chat_message</code>.
     */
    public final ChatMessage CHAT_MESSAGE = ChatMessage.CHAT_MESSAGE;

    /**
     * The table <code>chwimeet.chat_room</code>.
     */
    public final ChatRoom CHAT_ROOM = ChatRoom.CHAT_ROOM;

    /**
     * The table <code>chwimeet.member</code>.
     */
    public final Member MEMBER = Member.MEMBER;

    /**
     * The table <code>chwimeet.notification</code>.
     */
    public final Notification NOTIFICATION = Notification.NOTIFICATION;

    /**
     * The table <code>chwimeet.post</code>.
     */
    public final Post POST = Post.POST;

    /**
     * The table <code>chwimeet.post_favorite</code>.
     */
    public final PostFavorite POST_FAVORITE = PostFavorite.POST_FAVORITE;

    /**
     * The table <code>chwimeet.post_image</code>.
     */
    public final PostImage POST_IMAGE = PostImage.POST_IMAGE;

    /**
     * The table <code>chwimeet.post_option</code>.
     */
    public final PostOption POST_OPTION = PostOption.POST_OPTION;

    /**
     * The table <code>chwimeet.post_region</code>.
     */
    public final PostRegion POST_REGION = PostRegion.POST_REGION;

    /**
     * The table <code>chwimeet.region</code>.
     */
    public final Region REGION = Region.REGION;

    /**
     * The table <code>chwimeet.report</code>.
     */
    public final Report REPORT = Report.REPORT;

    /**
     * The table <code>chwimeet.reservation</code>.
     */
    public final Reservation RESERVATION = Reservation.RESERVATION;

    /**
     * The table <code>chwimeet.reservation_log</code>.
     */
    public final ReservationLog RESERVATION_LOG = ReservationLog.RESERVATION_LOG;

    /**
     * The table <code>chwimeet.reservation_option</code>.
     */
    public final ReservationOption RESERVATION_OPTION = ReservationOption.RESERVATION_OPTION;

    /**
     * The table <code>chwimeet.review</code>.
     */
    public final Review REVIEW = Review.REVIEW;

    /**
     * The table <code>chwimeet.vector_store</code>.
     */
    public final VectorStore VECTOR_STORE = VectorStore.VECTOR_STORE;

    /**
     * No further instances allowed
     */
    private Chwimeet() {
        super("chwimeet", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Category.CATEGORY,
            ChatMember.CHAT_MEMBER,
            ChatMessage.CHAT_MESSAGE,
            ChatRoom.CHAT_ROOM,
            Member.MEMBER,
            Notification.NOTIFICATION,
            Post.POST,
            PostFavorite.POST_FAVORITE,
            PostImage.POST_IMAGE,
            PostOption.POST_OPTION,
            PostRegion.POST_REGION,
            Region.REGION,
            Report.REPORT,
            Reservation.RESERVATION,
            ReservationLog.RESERVATION_LOG,
            ReservationOption.RESERVATION_OPTION,
            Review.REVIEW,
            VectorStore.VECTOR_STORE
        );
    }
}
